### ISSUE TITLE
Source of file

### ISSUE THREAD

**Issue by HVEC-lab** [steffelbauer/sea_level_rise_acceleration#1]
Compliments for publishing your source code and files in this way. I am trying to familiarise myself with your work.

Could you tell me the source of the file "nodal.nc"?

Thanks in advance.

Hessel Voortman

**Comment by steffelbauer** [comment]
Thank you very much for your interest.

The data contains the nodal cycle for different x-y coordinates and is the same as nodal_rsl.grd that you can find in this repository https://data.4tu.nl/articles/_/12688130/1

The reference paper for the data is Frederikse et al. (2016): https://doi.org/10.1002/2016GL070750

Hope that this answers your question.

Best wishes,
David

**Comment by HVEC-lab** [comment]
Certainly. Thank you for the prompt reply.
